「WebアプリからのDB利用」プラクティスの課題
Kassy0220/memo_app pull request #2
Opened 2022-07-25 05:16 UTC by Kassy0220

Sinatraで作成したメモアプリを、DBにメモを保存する様に変更しました。
ご確認をよろしくお願いいたします。

2022-07-30 15:40 UTC, u1tnk requested changes

2022-07-30 15:40 UTC, u1tnk commented on helpers/query_utils.rb
> +  def find_memo(id)
`find_memo` はidを指定して一件取得するメソッドなので、配列で返すのでは無く `Array#first` などを使って 一件返すようにしましょう。

2022-07-30 15:40 UTC, u1tnk commented on helpers/query_utils.rb
> +    connection.exec_prepared('find', params) do |result|
prepared statementちゃんと使ってますね 👍

2022-07-30 15:40 UTC, u1tnk commented on app.rb
>    memo_hash = memo.to_hash
せっかく `memo.title`などとシンプルに使えるオブジェクトにしているので、to_hashでhashにせずにそのままcreate_memoに渡せば良いと思います。

2022-07-31 09:08 UTC, Kassy0220 commented on helpers/query_utils.rb
> +  def find_memo(id)
ご指摘の通り、取得したメモを一件返すようにメソッドを変更しました。

https://github.com/Kassy0220/memo_app/blob/1a0badf92b47185bfe50c5be809653ce18f4f54a/helpers/query_utils.rb#L13-L21

上記と関連して、メモ作成時に作成したメモのIDを配列で返していたのですが、メモのIDを直接返す様にしています。

https://github.com/Kassy0220/memo_app/blob/1a0badf92b47185bfe50c5be809653ce18f4f54a/helpers/query_utils.rb#L23-L32

2022-07-31 09:14 UTC, Kassy0220 commented on app.rb
>    memo_hash = memo.to_hash
前回のメモアプリでハッシュを使用していた名残でそのままにしていました💦
`to_hash`はこの課題では全く不要なので削除しています。
https://github.com/Kassy0220/memo_app/blob/1a0badf92b47185bfe50c5be809653ce18f4f54a/memo.rb#L6-L16

作成したインスタンスをそのまま`create_memo`に渡しています。
https://github.com/Kassy0220/memo_app/blob/1a0badf92b47185bfe50c5be809653ce18f4f54a/app.rb#L27-L32
https://github.com/Kassy0220/memo_app/blob/1a0badf92b47185bfe50c5be809653ce18f4f54a/helpers/query_utils.rb#L23-L26

かなりスッキリしました！

2022-07-31 09:17 UTC, Kassy0220 commented
@u1tnk さん、ご確認ありがとうございます🙏

ご指摘の箇所を修正しましたので、ご確認をよろしくお願いいたします。

2022-08-01 02:16 UTC, u1tnk approved these changes

2022-08-01 02:16 UTC, u1tnk commented on helpers/query_utils.rb
> +  def find_memo(id)
そこちょっと気になったんですが、`to_a`で良いか確信が持てなくてスルーしてしまったところでした… 🙏 
スッキリしました 👍

2022-08-01 10:01 UTC, merged